In [2]:
import tensorflow as tf
import numpy as np
import os
import pathlib
from tensorflow import keras

In [3]:
#Newsgroup20dataset->20000 messages with 20 different topic categories
data_path=tf.keras.utils.get_file(
    'news20.tar.gz',
    'http://www.cs.cmu.edu/afs/cs.cmu.edu/project/theo-20/www/data/news20.tar.gz',
    untar=True)

17334272/17329808 [==============================] - 13s 1us/step


In [4]:
print(data_path)

/root/.keras/datasets/news20.tar.gz


In [6]:
os.path.dirname(data_path)

'/root/.keras/datasets'

In [5]:
data_dir=os.path.join(os.path.dirname(data_path),'20_newsgroup')
dirnames=os.listdir(data_dir)
print('Number of directories:',len(dirnames))
print('Directory names:',dirnames)

Number of directories: 20
Directory names: ['comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'sci.electronics', 'misc.forsale', 'sci.med', 'talk.religion.misc', 'alt.atheism', 'sci.crypt', 'rec.autos', 'talk.politics.guns', 'comp.graphics', 'soc.religion.christian', 'rec.sport.hockey', 'comp.windows.x', 'rec.motorcycles', 'sci.space', 'rec.sport.baseball', 'talk.politics.misc', 'talk.politics.mideast']


In [ ]:
print(data_dir)

/root/.keras/datasets/20_newsgroup


In [ ]:
fnames=os.listdir(os.path.join(data_dir,'comp.graphics'))
print('Number of files in comp.graphics:',len(fnames))
print('Some example filenames:',fnames[:5])

Number of files in comp.graphics: 1000
Some example filenames: ['38454', '38360', '39669', '38236', '38601']


In [ ]:
fnames=os.listdir(os.path.join(data_dir,'talk.politics.mideast'))
print('Number of files in talk.politics.mideast:',len(fnames))
print('Some example filenames:',fnames[:5])

Number of files in talk.politics.mideast: 1000
Some example filenames: ['77266', '77207', '76351', '76421', '77813']


In [ ]:
print(open(os.path.join(data_dir,'comp.graphics','38987')).read())

Newsgroups: comp.graphics
Path: cantaloupe.srv.cs.cmu.edu!das-news.harvard.edu!noc.near.net!howland.reston.ans.net!agate!dog.ee.lbl.gov!network.ucsd.edu!usc!rpi!nason110.its.rpi.edu!mabusj
From: mabusj@nason110.its.rpi.edu (Jasen M. Mabus)
Subject: Looking for Brain in CAD
Message-ID: <c285m+p@rpi.edu>
Nntp-Posting-Host: nason110.its.rpi.edu
Reply-To: mabusj@rpi.edu
Organization: Rensselaer Polytechnic Institute, Troy, NY.
Date: Thu, 29 Apr 1993 23:27:20 GMT
Lines: 7

Jasen Mabus
RPI student

	I am looking for a hman brain in any CAD (.dxf,.cad,.iges,.cgm,etc.) or picture (.gif,.jpg,.ras,etc.) format for an animation demonstration. If any has or knows of a location please reply by e-mail to mabusj@rpi.edu.

Thank you in advance,
Jasen Mabus  



In [ ]:
print(open(os.path.join(data_dir,'talk.politics.mideast','77266')).read())

Path: cantaloupe.srv.cs.cmu.edu!das-news.harvard.edu!noc.near.net!howland.reston.ans.net!usc!news.service.uci.edu!orion.oac.uci.edu!tclock
From: tclock@orion.oac.uci.edu (Tim Clock)
Subject: Re: Pease without justice cann't last Re: Last Opportunity for Peace
Nntp-Posting-Host: orion.oac.uci.edu
Message-ID: <2BF18745.17290@news.service.uci.edu>
Newsgroups: talk.politics.mideast
Organization: University of California, Irvine
Lines: 53
Date: 12 May 93 23:24:53 GMT
References: <1993Apr30.083345.15696@nuscc.nus.sg> <C6xKnC.285@ulowell.ulowell.edu>

In article <C6xKnC.285@ulowell.ulowell.edu> cshi@cs.ulowell.edu (Godada Shi) writes:
>In article <1993Apr30.083345.15696@nuscc.nus.sg> eng10511@nusunix1.nus.sg (RAM VIKASH TIWARY) writes:
>>
>>Now that all the parties are back to the negotiating table, the stakes 
>>as I see is are indeed high and the future stability of the region and 
>>perhaps the world is in the balance.
>>
>>	While Israel continues to refuse to talk to the PLO, labelling
>>

In [7]:
samples=[]
labels=[]
class_names=[]
class_index=0
for dirname in sorted(os.listdir(data_dir)):
  class_names.append(dirname)
  dirpath=os.path.join(data_dir,dirname)
  fnames=os.listdir(dirpath)
  print('Processing %s,%d files found' % (dirname,len(fnames)))
  for fname in fnames:
    fpath=os.path.join(dirpath,fname)
    f=open(fpath,encoding='latin-1')
    content=f.read()
    lines=content.split('\n')
    lines=lines[10:]
    content='\n'.join(lines)
    samples.append(content)
    labels.append(class_index)
  class_index+=1

print('Classes:',class_names)
print('Number of samples:',len(samples))    


Processing alt.atheism,1000 files found
Processing comp.graphics,1000 files found
Processing comp.os.ms-windows.misc,1000 files found
Processing comp.sys.ibm.pc.hardware,1000 files found
Processing comp.sys.mac.hardware,1000 files found
Processing comp.windows.x,1000 files found
Processing misc.forsale,1000 files found
Processing rec.autos,1000 files found
Processing rec.motorcycles,1000 files found
Processing rec.sport.baseball,1000 files found
Processing rec.sport.hockey,1000 files found
Processing sci.crypt,1000 files found
Processing sci.electronics,1000 files found
Processing sci.med,1000 files found
Processing sci.space,1000 files found
Processing soc.religion.christian,997 files found
Processing talk.politics.guns,1000 files found
Processing talk.politics.mideast,1000 files found
Processing talk.politics.misc,1000 files found
Processing talk.religion.misc,1000 files found
Classes: ['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.m

In [ ]:
samples[1000]

'boat, but it could be anything.  On the drawing you have a set of\nreference points whose true x,y positions are known.  \n\nNow you digitize the drawing manually (in this case, using Yaron\nDanon\'s excellent Digitize program).  That is, you use a program which\nconverts cursor positions to x,y and saves those values when you click\nthe mouse.\n\nUpon digitizing you notice that the reference point values that come\nout of the digitizing process differ in small but significant ways\nfrom the known true values.  This is understandable because the\nscanned drawing is a reproduction of the original and there are\nsuccessive sources of distortion such as differential expansion and\ncontraction of paper, errors introduced in the printing process,\nscanner errors and what have you.\n\nThe errors are not uniform over the entire drawing, so "global"\nadjustments such as stretching/contracting uniformly over x or y, or\nrotating the whole drawing, are not satisfactory.\n\nSo the question is: d

In [ ]:
samples[1000].split('\n')

['boat, but it could be anything.  On the drawing you have a set of',
 'reference points whose true x,y positions are known.  ',
 '',
 'Now you digitize the drawing manually (in this case, using Yaron',
 "Danon's excellent Digitize program).  That is, you use a program which",
 'converts cursor positions to x,y and saves those values when you click',
 'the mouse.',
 '',
 'Upon digitizing you notice that the reference point values that come',
 'out of the digitizing process differ in small but significant ways',
 'from the known true values.  This is understandable because the',
 'scanned drawing is a reproduction of the original and there are',
 'successive sources of distortion such as differential expansion and',
 'contraction of paper, errors introduced in the printing process,',
 'scanner errors and what have you.',
 '',
 'The errors are not uniform over the entire drawing, so "global"',
 'adjustments such as stretching/contracting uniformly over x or y, or',
 'rotating the whole d

In [ ]:
labels[-10:]

[19, 19, 19, 19, 19, 19, 19, 19, 19, 19]

In [ ]:
from sklearn.model_selection import train_test_split
train_samples,val_samples,train_label,val_label=train_test_split(
    samples,labels,test_size=0.2)

In [ ]:
train_samples[2232]

'Date: Mon, 5 Apr 1993 23:38:33 GMT\nLines: 20\n\n \nPanasonic KX-T3000H, Combo black cordless & speaker phone all in one.\n new- $160, now- $100 + shipping OBO.\n \nCurtis Mathes VHS VCR Remote included and it works with universal remotes.\n Works great but I replaced it with a Stereo VCR.\n paid $300 years ago, will sell for $125 delivered OBO.\n \nRadio Shack stereo amp.  2 inputs, tone, and left and right volume.  Speakers\n not included.  $20 plus shipping.\n \nIf you are interested in either of the above mail me at\n radley@gibbs.out.unc.edu.\n\n        _\n    _  //       Major: Computer Science              /<eith Radley\n    \\\\//        Minor:     English              Radley@gibbs.oit.unc.edu\n     \\/      Computer:   AMIGA 3000           University of North Carolina\n\n\n'

In [ ]:
val_samples[1332]

"References: <93109.231733ISSCCK@BYUVM.BITNET> <wcscps.735321331@cunews> <C5tAow.6oD@dscomsa.desy.de> <GERRY.93Apr21130354@onion.cmu.edu>\nDate: Thu, 22 Apr 1993 01:06:11 GMT\n\n\nIn article <GERRY.93Apr21130354@onion.cmu.edu>, gerry@cmu.edu (Gerry Roston) writes:\n|>In  hallam@dscomsa.desy.de (Phill Hallam-Baker) writes:\n|>\n|>   The founding fathers of the US were hardly great on religious freedoms. At\n|>   least one history I have read formed the opinion that they left for the\n|>   US not to practice religious freedom but to practice religious intolerance.\n|>\n|>Sigh, see what our school systems are producing?  Total confusion!\n|>The original English settlers were, probably, the most intolerant lot\n|>of people to ever assemble.  However, the Founding Fathers\n|>(Washington, Jefferson, Madison, etc.), practically made it their\n|>life's work to ensure that religious intolerance would not destroy\n|>their great experiment... a democratic republic.\n\n\nPilgrim ... Founding forgo

In [ ]:
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

vectorizer=TextVectorization(max_tokens=20000,output_sequence_length=200)
text_ds=tf.data.Dataset.from_tensor_slices(train_samples).batch(128)
vectorizer.adapt(text_ds)

In [ ]:
next(iter(text_ds))

<tf.Tensor: shape=(128,), dtype=string, numpy=
array([b'\n\n\nArticle 10886 of alt.radio.scanner:\nPath: usenet.ins.cwru.edu!cleveland.Freenet.Edu!aj008\nFrom: aj008@cleveland.Freenet.Edu (Aaron M. Barnes)\n>Newsgroups: alt.radio.scanner\nSubject: Realistic PRO-2024 for sale-was $200,sell for $150 obo\nDate: 20 Apr 1993 16:01:28 GMT\nOrganization: Case Western Reserve University, Cleveland, Ohio (USA)\nLines: 26\nMessage-ID: <1r16oo$3du@usenet.INS.CWRU.Edu>\nNNTP-Posting-Host: slc10.ins.cwru.edu\n\n\nHello.\n\nI have a Realistic PRO-2024 scanner for sale.Here is a small desc\nription:\n\n60 programible chanels\nfully detailed backlighted digital display\nheadphone jack\nantenna jack\nremovable telescoping antenna\nauto search\n\ncoverage:\n30-50mHz\n118-174mHz\n380-512mHz\n\nIt originally cost $200, but I will sell for $150.\n\nThank You.\n-- \n       / /     Buchanan in `96!\n      / /      Fear the goverment that fears your guns.\n  \\ \\/ /       Without the 2nd amendment, we cannot

In [ ]:
vectorizer.get_vocabulary()[:15]

['',
 '[UNK]',
 'the',
 'to',
 'of',
 'a',
 'and',
 'in',
 'is',
 'i',
 'that',
 'it',
 'for',
 'you',
 'this']

In [ ]:
output=vectorizer([['I love deep learning']])
output

<tf.Tensor: shape=(1, 200), dtype=int64, numpy=
array([[   9,  431, 2379, 2617,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,   

In [ ]:
output=vectorizer([["the cat sat on the mat"]])
output.numpy()[0,:6]

array([   2, 3649, 1725,   15,    2, 6016])

In [ ]:
voc=vectorizer.get_vocabulary()
word_index=dict(zip(voc,range(len(voc))))

In [ ]:
len(word_index)

20000

In [ ]:
test=["the", "cat", "sat", "on", "the", "mat"]
[word_index[w] for w in test]

[2, 3649, 1725, 15, 2, 6016]

In [ ]:
!wget http://nlp.stanford.edu/data/glove.6B.zip
!unzip -q glove.6B.zip

--2020-10-07 15:34:50--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2020-10-07 15:34:50--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2020-10-07 15:34:50--  http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glove.6

In [ ]:
with open('glove.6B.100d.txt','r') as f:
  content1=f.readline()
  print(content1)
  content2=f.readline()
  print(content2)
  content3=f.readline()
  print(content3)

the -0.038194 -0.24487 0.72812 -0.39961 0.083172 0.043953 -0.39141 0.3344 -0.57545 0.087459 0.28787 -0.06731 0.30906 -0.26384 -0.13231 -0.20757 0.33395 -0.33848 -0.31743 -0.48336 0.1464 -0.37304 0.34577 0.052041 0.44946 -0.46971 0.02628 -0.54155 -0.15518 -0.14107 -0.039722 0.28277 0.14393 0.23464 -0.31021 0.086173 0.20397 0.52624 0.17164 -0.082378 -0.71787 -0.41531 0.20335 -0.12763 0.41367 0.55187 0.57908 -0.33477 -0.36559 -0.54857 -0.062892 0.26584 0.30205 0.99775 -0.80481 -3.0243 0.01254 -0.36942 2.2167 0.72201 -0.24978 0.92136 0.034514 0.46745 1.1079 -0.19358 -0.074575 0.23353 -0.052062 -0.22044 0.057162 -0.15806 -0.30798 -0.41625 0.37972 0.15006 -0.53212 -0.2055 -1.2526 0.071624 0.70565 0.49744 -0.42063 0.26148 -1.538 -0.30223 -0.073438 -0.28312 0.37104 -0.25217 0.016215 -0.017099 -0.38984 0.87424 -0.72569 -0.51058 -0.52028 -0.1459 0.8278 0.27062

, -0.10767 0.11053 0.59812 -0.54361 0.67396 0.10663 0.038867 0.35481 0.06351 -0.094189 0.15786 -0.81665 0.14172 0.21939 0.58505 -0.52158

In [ ]:
embeddings_index={}
with open('glove.6B.100d.txt') as f:
    for line in f:
        word,coefs=line.split(maxsplit=1)
        coefs=np.fromstring(coefs, "f", sep=" ")
        embeddings_index[word]=coefs

print("Found %s word vectors." % len(embeddings_index))

Found 400000 word vectors.


In [ ]:
embeddings_index['the']

array([-0.038194, -0.24487 ,  0.72812 , -0.39961 ,  0.083172,  0.043953,
       -0.39141 ,  0.3344  , -0.57545 ,  0.087459,  0.28787 , -0.06731 ,
        0.30906 , -0.26384 , -0.13231 , -0.20757 ,  0.33395 , -0.33848 ,
       -0.31743 , -0.48336 ,  0.1464  , -0.37304 ,  0.34577 ,  0.052041,
        0.44946 , -0.46971 ,  0.02628 , -0.54155 , -0.15518 , -0.14107 ,
       -0.039722,  0.28277 ,  0.14393 ,  0.23464 , -0.31021 ,  0.086173,
        0.20397 ,  0.52624 ,  0.17164 , -0.082378, -0.71787 , -0.41531 ,
        0.20335 , -0.12763 ,  0.41367 ,  0.55187 ,  0.57908 , -0.33477 ,
       -0.36559 , -0.54857 , -0.062892,  0.26584 ,  0.30205 ,  0.99775 ,
       -0.80481 , -3.0243  ,  0.01254 , -0.36942 ,  2.2167  ,  0.72201 ,
       -0.24978 ,  0.92136 ,  0.034514,  0.46745 ,  1.1079  , -0.19358 ,
       -0.074575,  0.23353 , -0.052062, -0.22044 ,  0.057162, -0.15806 ,
       -0.30798 , -0.41625 ,  0.37972 ,  0.15006 , -0.53212 , -0.2055  ,
       -1.2526  ,  0.071624,  0.70565 ,  0.49744 , 

In [ ]:
np.fromstring('1.2 2.3','f', sep=' ')

array([1.2, 2.3], dtype=float32)

In [ ]:
print(embeddings_index.get('dbz'))

None


In [ ]:
num_tokens=len(voc)+2
embedding_dim=100
hits=0
misses=0

embedding_matrix=np.zeros((num_tokens,embedding_dim))
for word,i in word_index.items():
  embedding_vector=embeddings_index.get(word)
  if embedding_vector is not None:
    embedding_matrix[i]=embedding_vector
    hits+=1
  else:
    misses+=1

print('Converted %d words (%d misses)' %(hits,misses))  

Converted 17936 words (2064 misses)


In [ ]:
embedding_matrix.shape

(20002, 100)

In [ ]:
len(train_samples),len(train_label)

(15997, 15997)

In [ ]:
type(train_samples)

list

In [ ]:
len(val_samples),len(val_label)

(4000, 4000)

In [ ]:
embedding_layer=tf.keras.layers.Embedding(num_tokens,embedding_dim,
                                          embeddings_initializer=tf.keras.initializers.Constant(embedding_matrix),
                                          trainable=False,)                                        

In [ ]:
model=tf.keras.Sequential([                      
    embedding_layer,
    tf.keras.layers.Conv1D(128,5,activation='relu'),
    tf.keras.layers.MaxPooling1D(5),
    tf.keras.layers.Conv1D(128,5,activation='relu'),
    tf.keras.layers.MaxPooling1D(5),
    tf.keras.layers.Conv1D(128,5,activation='relu'),
    tf.keras.layers.MaxPooling1D(5),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(len(class_names),activation='softmax')])

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 100)         2000200   
_________________________________________________________________
conv1d_6 (Conv1D)            (None, None, 128)         64128     
_________________________________________________________________
max_pooling1d_3 (MaxPooling1 (None, None, 128)         0         
_________________________________________________________________
conv1d_7 (Conv1D)            (None, None, 128)         82048     
_________________________________________________________________
max_pooling1d_4 (MaxPooling1 (None, None, 128)         0         
_________________________________________________________________
conv1d_8 (Conv1D)            (None, None, 128)         82048     
_________________________________________________________________
max_pooling1d_5 (MaxPooling1 (None, None, 128)        

In [ ]:
x_train=vectorizer(np.array([[s] for s in train_samples])).numpy()
x_val=vectorizer(np.array([[s] for s in val_samples])).numpy()

y_train=np.array(train_labels)
y_val=np.array(val_labels)

In [ ]:
model.compile(
    loss="sparse_categorical_crossentropy", optimizer="rmsprop", metrics=["acc"])

model.fit(x_train, y_train, batch_size=128, epochs=20, validation_data=(x_val, y_val))