In [1]:
import tensorflow as tf
import numpy as np
import os
import pathlib
from tensorflow import keras

In [2]:
#Newsgroup20dataset->20000 messages with 20 different topic categories
data_path=tf.keras.utils.get_file(
    'news20.tar.gz',
    'http://www.cs.cmu.edu/afs/cs.cmu.edu/project/theo-20/www/data/news20.tar.gz',
    untar=True)

17334272/17329808 [==============================] - 9s 1us/step


In [4]:
print(data_path)

/root/.keras/datasets/news20.tar.gz


In [5]:
os.path.dirname(data_path)

'/root/.keras/datasets'

In [6]:
data_dir=os.path.join(os.path.dirname(data_path),'20_newsgroup')
dirnames=os.listdir(data_dir)
print('Number of directories:',len(dirnames))
print('Directory names:',dirnames)

Number of directories: 20
Directory names: ['comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'sci.electronics', 'misc.forsale', 'sci.med', 'talk.religion.misc', 'alt.atheism', 'sci.crypt', 'rec.autos', 'talk.politics.guns', 'comp.graphics', 'soc.religion.christian', 'rec.sport.hockey', 'comp.windows.x', 'rec.motorcycles', 'sci.space', 'rec.sport.baseball', 'talk.politics.misc', 'talk.politics.mideast']


In [7]:
print(data_dir)

/root/.keras/datasets/20_newsgroup


In [8]:
fnames=os.listdir(os.path.join(data_dir,'comp.graphics'))
print('Number of files in comp.graphics:',len(fnames))
print('Some example filenames:',fnames[:5])

Number of files in comp.graphics: 1000
Some example filenames: ['38740', '38967', '38491', '39655', '38250']


In [9]:
fnames=os.listdir(os.path.join(data_dir,'talk.politics.mideast'))
print('Number of files in talk.politics.mideast:',len(fnames))
print('Some example filenames:',fnames[:5])

Number of files in talk.politics.mideast: 1000
Some example filenames: ['75916', '77221', '76074', '75951', '76363']


In [10]:
print(open(os.path.join(data_dir,'comp.graphics','38987')).read())

Newsgroups: comp.graphics
Path: cantaloupe.srv.cs.cmu.edu!das-news.harvard.edu!noc.near.net!howland.reston.ans.net!agate!dog.ee.lbl.gov!network.ucsd.edu!usc!rpi!nason110.its.rpi.edu!mabusj
From: mabusj@nason110.its.rpi.edu (Jasen M. Mabus)
Subject: Looking for Brain in CAD
Message-ID: <c285m+p@rpi.edu>
Nntp-Posting-Host: nason110.its.rpi.edu
Reply-To: mabusj@rpi.edu
Organization: Rensselaer Polytechnic Institute, Troy, NY.
Date: Thu, 29 Apr 1993 23:27:20 GMT
Lines: 7

Jasen Mabus
RPI student

	I am looking for a hman brain in any CAD (.dxf,.cad,.iges,.cgm,etc.) or picture (.gif,.jpg,.ras,etc.) format for an animation demonstration. If any has or knows of a location please reply by e-mail to mabusj@rpi.edu.

Thank you in advance,
Jasen Mabus  



In [11]:
print(open(os.path.join(data_dir,'talk.politics.mideast','77266')).read())

Path: cantaloupe.srv.cs.cmu.edu!das-news.harvard.edu!noc.near.net!howland.reston.ans.net!usc!news.service.uci.edu!orion.oac.uci.edu!tclock
From: tclock@orion.oac.uci.edu (Tim Clock)
Subject: Re: Pease without justice cann't last Re: Last Opportunity for Peace
Nntp-Posting-Host: orion.oac.uci.edu
Message-ID: <2BF18745.17290@news.service.uci.edu>
Newsgroups: talk.politics.mideast
Organization: University of California, Irvine
Lines: 53
Date: 12 May 93 23:24:53 GMT
References: <1993Apr30.083345.15696@nuscc.nus.sg> <C6xKnC.285@ulowell.ulowell.edu>

In article <C6xKnC.285@ulowell.ulowell.edu> cshi@cs.ulowell.edu (Godada Shi) writes:
>In article <1993Apr30.083345.15696@nuscc.nus.sg> eng10511@nusunix1.nus.sg (RAM VIKASH TIWARY) writes:
>>
>>Now that all the parties are back to the negotiating table, the stakes 
>>as I see is are indeed high and the future stability of the region and 
>>perhaps the world is in the balance.
>>
>>	While Israel continues to refuse to talk to the PLO, labelling
>>

In [12]:
samples=[]
labels=[]
class_names=[]
class_index=0
for dirname in sorted(os.listdir(data_dir)):
  class_names.append(dirname)
  dirpath=os.path.join(data_dir,dirname)
  fnames=os.listdir(dirpath)
  print('Processing %s,%d files found'.format(dirname,len(fnames)))
  for fname in fnames:
    fpath=os.path.join(dirpath,fname)
    f=open(fpath,encoding='latin-1')
    content=f.read()
    lines=content.split('\n')
    lines=lines[10:]
    content='\n'.join(lines)
    samples.append(content)
    labels.append(class_index)
  class_index+=1

print('Classes:',class_names)
print('Number of samples:',len(samples))    


Processing %s,%d files found
Processing %s,%d files found
Processing %s,%d files found
Processing %s,%d files found
Processing %s,%d files found
Processing %s,%d files found
Processing %s,%d files found
Processing %s,%d files found
Processing %s,%d files found
Processing %s,%d files found
Processing %s,%d files found
Processing %s,%d files found
Processing %s,%d files found
Processing %s,%d files found
Processing %s,%d files found
Processing %s,%d files found
Processing %s,%d files found
Processing %s,%d files found
Processing %s,%d files found
Processing %s,%d files found
Classes: ['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc', 'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware', 'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles', 'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt', 'sci.electronics', 'sci.med', 'sci.space', 'soc.religion.christian', 'talk.politics.guns', 'talk.politics.mideast', 'talk.politics.misc', 'talk.religion.misc']
Number of samples

In [13]:
samples[1000]

'\nIf you want to have Soft-Scrolling on your VGA, you have to change some \nintern registers of the CRTC. But it is a little bit difficult to explain, \nso I would suggest, you take a look at "The Programming of the \nEGA/VGA-Adapter" by Addison-Wesley. You will find all useful descriptions \nfor every available VGA-Register.\n\n-Boris\n\n---\ndr_bobo@ponton.hanse.de                 ---> Boris Pruessmann\n'

In [14]:
samples[1000].split('\n')

['',
 'If you want to have Soft-Scrolling on your VGA, you have to change some ',
 'intern registers of the CRTC. But it is a little bit difficult to explain, ',
 'so I would suggest, you take a look at "The Programming of the ',
 'EGA/VGA-Adapter" by Addison-Wesley. You will find all useful descriptions ',
 'for every available VGA-Register.',
 '',
 '-Boris',
 '',
 '---',
 'dr_bobo@ponton.hanse.de                 ---> Boris Pruessmann',
 '']

In [15]:
labels[-10:]

[19, 19, 19, 19, 19, 19, 19, 19, 19, 19]

In [16]:
from sklearn.model_selection import train_test_split
train_samples,val_samples,train_label,val_label=train_test_split(
    samples,labels,test_size=0.2)

In [ ]:
train_samples[2232]

In [ ]:
val_samples[1332]

In [28]:
tokenizer=tf.keras.preprocessing.text.Tokenizer(filters='')
tokenizer.fit_on_texts(train_samples)
x_train=tokenizer.texts_to_sequences(train_samples)
x_train=tf.keras.preprocessing.sequence.pad_sequences(x_train,256,padding='post')

In [32]:
y_train=tf.constant(train_label)
train_dataset=tf.data.Dataset.from_tensor_slices((x_train,y_train))

In [33]:
BUFFER_SIZE=10000
train_dataset=train_dataset.shuffle(BUFFER_SIZE).batch(128,drop_remainder=True)

In [34]:
next(iter(train_dataset))

(<tf.Tensor: shape=(128, 256), dtype=int32, numpy=
 array([[307901,   2721,   1539, ...,      0,      0,      0],
        [    12,     39,     19, ..., 100876,    149, 100877],
        [   159,     40, 243053, ...,      0,      0,      0],
        ...,
        [  1365,  17387,   9915, ...,      0,      0,      0],
        [   109, 195276, 195277, ...,      0,      0,      0],
        [307798,     32,     17, ...,  10117,   5022,  10874]], dtype=int32)>,
 <tf.Tensor: shape=(128,), dtype=int32, numpy=
 array([ 6, 18,  0,  9, 17, 14, 13,  0,  1,  5, 18,  8, 10, 11, 19,  8,  2,
        13, 19, 14,  6, 11,  4,  4,  2,  9,  0, 19, 10, 19,  1, 11,  6,  5,
        11,  3,  1,  0, 19, 12, 11, 11, 14, 18,  0,  7,  9,  2, 17,  8, 17,
         7,  7, 10, 12,  3,  6,  3,  3,  6,  9,  9, 12, 10,  3,  1,  3,  0,
        19,  8,  7,  6, 18, 15,  9,  1, 16,  3, 15, 10,  1, 18,  3,  1,  2,
         6, 19, 10, 10,  9, 19,  4,  2, 17,  9,  5, 14,  2,  3, 14,  9,  4,
         4,  4,  6,  2,  5, 11,  3, 10,

In [40]:
x_val=tokenizer.texts_to_sequences(val_samples)
x_val=tf.keras.preprocessing.sequence.pad_sequences(x_val,256,padding='post')

y_val=tf.constant(val_label)
validation_dataset=tf.data.Dataset.from_tensor_slices((x_val,y_val))
validation_dataset=validation_dataset.batch(128,drop_remainder=True)

In [36]:
#dictionary of word index
word_index=tokenizer.word_index

In [37]:
len(word_index)

483677

In [29]:
x_train.shape

(15997, 256)

In [38]:
test=["the", "cat", "sat", "on", "the", "mat"]
[word_index[w] for w in test]

[1, 4216, 4684, 14, 1, 10357]

In [39]:
!wget http://nlp.stanford.edu/data/glove.6B.zip
!unzip -q glove.6B.zip

--2020-10-08 10:10:37--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2020-10-08 10:10:38--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2020-10-08 10:10:38--  http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glove.6

In [41]:
with open('glove.6B.100d.txt','r') as f:
  content1=f.readline()
  print(content1)
  content2=f.readline()
  print(content2)
  content3=f.readline()
  print(content3)

the -0.038194 -0.24487 0.72812 -0.39961 0.083172 0.043953 -0.39141 0.3344 -0.57545 0.087459 0.28787 -0.06731 0.30906 -0.26384 -0.13231 -0.20757 0.33395 -0.33848 -0.31743 -0.48336 0.1464 -0.37304 0.34577 0.052041 0.44946 -0.46971 0.02628 -0.54155 -0.15518 -0.14107 -0.039722 0.28277 0.14393 0.23464 -0.31021 0.086173 0.20397 0.52624 0.17164 -0.082378 -0.71787 -0.41531 0.20335 -0.12763 0.41367 0.55187 0.57908 -0.33477 -0.36559 -0.54857 -0.062892 0.26584 0.30205 0.99775 -0.80481 -3.0243 0.01254 -0.36942 2.2167 0.72201 -0.24978 0.92136 0.034514 0.46745 1.1079 -0.19358 -0.074575 0.23353 -0.052062 -0.22044 0.057162 -0.15806 -0.30798 -0.41625 0.37972 0.15006 -0.53212 -0.2055 -1.2526 0.071624 0.70565 0.49744 -0.42063 0.26148 -1.538 -0.30223 -0.073438 -0.28312 0.37104 -0.25217 0.016215 -0.017099 -0.38984 0.87424 -0.72569 -0.51058 -0.52028 -0.1459 0.8278 0.27062

, -0.10767 0.11053 0.59812 -0.54361 0.67396 0.10663 0.038867 0.35481 0.06351 -0.094189 0.15786 -0.81665 0.14172 0.21939 0.58505 -0.52158

In [42]:
embeddings_index={}
with open('glove.6B.100d.txt') as f:
    for line in f:
        word,coefs=line.split(maxsplit=1)
        coefs=np.fromstring(coefs, "f", sep=" ")
        embeddings_index[word]=coefs

print("Found %s word vectors." % len(embeddings_index))

Found 400000 word vectors.


In [43]:
embeddings_index['the']

array([-0.038194, -0.24487 ,  0.72812 , -0.39961 ,  0.083172,  0.043953,
       -0.39141 ,  0.3344  , -0.57545 ,  0.087459,  0.28787 , -0.06731 ,
        0.30906 , -0.26384 , -0.13231 , -0.20757 ,  0.33395 , -0.33848 ,
       -0.31743 , -0.48336 ,  0.1464  , -0.37304 ,  0.34577 ,  0.052041,
        0.44946 , -0.46971 ,  0.02628 , -0.54155 , -0.15518 , -0.14107 ,
       -0.039722,  0.28277 ,  0.14393 ,  0.23464 , -0.31021 ,  0.086173,
        0.20397 ,  0.52624 ,  0.17164 , -0.082378, -0.71787 , -0.41531 ,
        0.20335 , -0.12763 ,  0.41367 ,  0.55187 ,  0.57908 , -0.33477 ,
       -0.36559 , -0.54857 , -0.062892,  0.26584 ,  0.30205 ,  0.99775 ,
       -0.80481 , -3.0243  ,  0.01254 , -0.36942 ,  2.2167  ,  0.72201 ,
       -0.24978 ,  0.92136 ,  0.034514,  0.46745 ,  1.1079  , -0.19358 ,
       -0.074575,  0.23353 , -0.052062, -0.22044 ,  0.057162, -0.15806 ,
       -0.30798 , -0.41625 ,  0.37972 ,  0.15006 , -0.53212 , -0.2055  ,
       -1.2526  ,  0.071624,  0.70565 ,  0.49744 , 

In [44]:
np.fromstring('1.2 2.3','f', sep=' ')

array([1.2, 2.3], dtype=float32)

In [45]:
print(embeddings_index.get('dbz'))

None


In [47]:
num_tokens=len(word_index)+2
embedding_dim=100
hits=0
misses=0

embedding_matrix=np.zeros((num_tokens,embedding_dim))
for word,i in word_index.items():
  embedding_vector=embeddings_index.get(word)
  if embedding_vector is not None:
    embedding_matrix[i]=embedding_vector
    hits+=1
  else:
    misses+=1

print('Converted %d words (%d misses)' %(hits,misses))  

Converted 49791 words (433886 misses)


In [48]:
embedding_matrix.shape

(483679, 100)

In [ ]:
len(val_samples),len(val_label)

(4000, 4000)

In [50]:
embedding_layer=tf.keras.layers.Embedding(num_tokens,embedding_dim,
                                          embeddings_initializer=tf.keras.initializers.Constant(embedding_matrix),
                                          trainable=False,)                                        

In [51]:
model=tf.keras.Sequential([                      
    embedding_layer,
    tf.keras.layers.Conv1D(128,5,activation='relu'),
    tf.keras.layers.MaxPooling1D(5),
    tf.keras.layers.Conv1D(128,5,activation='relu'),
    tf.keras.layers.MaxPooling1D(5),
    tf.keras.layers.Conv1D(128,5,activation='relu'),
    tf.keras.layers.MaxPooling1D(5),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(len(class_names),activation='softmax')])

In [52]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 100)         48367900  
_________________________________________________________________
conv1d (Conv1D)              (None, None, 128)         64128     
_________________________________________________________________
max_pooling1d (MaxPooling1D) (None, None, 128)         0         
_________________________________________________________________
conv1d_1 (Conv1D)            (None, None, 128)         82048     
_________________________________________________________________
max_pooling1d_1 (MaxPooling1 (None, None, 128)         0         
_________________________________________________________________
conv1d_2 (Conv1D)            (None, None, 128)         82048     
_________________________________________________________________
max_pooling1d_2 (MaxPooling1 (None, None, 128)         0

In [53]:
model.compile(
    loss="sparse_categorical_crossentropy", optimizer="rmsprop", metrics=["acc"])

model.fit(train_dataset, batch_size=128, epochs=20, validation_data=validation_dataset)

Epoch 1/20
124/124 [==============================] - 37s 298ms/step - loss: 2.7695 - acc: 0.1195 - val_loss: 2.3628 - val_acc: 0.1852
Epoch 2/20
124/124 [==============================] - 37s 299ms/step - loss: 2.0879 - acc: 0.2872 - val_loss: 1.7190 - val_acc: 0.4103
Epoch 3/20
124/124 [==============================] - 38s 306ms/step - loss: 1.6526 - acc: 0.4267 - val_loss: 1.3624 - val_acc: 0.5255
Epoch 4/20
124/124 [==============================] - 37s 297ms/step - loss: 1.4056 - acc: 0.5185 - val_loss: 1.3898 - val_acc: 0.5199
Epoch 5/20
124/124 [==============================] - 37s 296ms/step - loss: 1.2586 - acc: 0.5660 - val_loss: 1.2040 - val_acc: 0.5917
Epoch 6/20
124/124 [==============================] - 37s 297ms/step - loss: 1.1267 - acc: 0.6169 - val_loss: 1.1717 - val_acc: 0.6038
Epoch 7/20
124/124 [==============================] - 36s 294ms/step - loss: 1.0223 - acc: 0.6541 - val_loss: 1.1554 - val_acc: 0.6240
Epoch 8/20
124/124 [==============================] - 3